var allMonsters = {
	"Ape": "https://roll20.net/compendium/dnd5e/Ape",
    "Axe Beak": "https://roll20.net/compendium/dnd5e/Axe%20Beak",
    "Black Bear": "https://roll20.net/compendium/dnd5e/Black%20Bear",
    "Boar": "https://roll20.net/compendium/dnd5e/Boar",
    "Brown Bear": "https://roll20.net/compendium/dnd5e/Brown%20Bear",
    "Cave Bear": "http://monstercards.ca/5esrd/cave-bear",
    "Constrictor Snake": "https://roll20.net/compendium/dnd5e/Constrictor%20Snake",
    "Crocodile": "https://roll20.net/compendium/dnd5e/Crocodile",
    "Dire Wolf": "https://roll20.net/compendium/dnd5e/Dire%20Wolf",
    "Elk": "https://roll20.net/compendium/dnd5e/Elk",
    "Female Steeder": "https://5e.tools/bestiary/female-steeder-mtf.html",
    "Giant Badger": "https://roll20.net/compendium/dnd5e/Giant%20Badger",
    "Giant Bat": "https://roll20.net/compendium/dnd5e/Giant%20Bat",
    "Giant Boar": "https://roll20.net/compendium/dnd5e/Giant%20Boar",
    "Giant Centipede": "https://roll20.net/compendium/dnd5e/Giant%20Centipede",
    "Giant Constrictor Snake": "https://roll20.net/compendium/dnd5e/Giant%20Constrictor%20Snake",
    "Giant Eagle": "https://roll20.net/compendium/dnd5e/Giant%20Eagle",
    "Giant Elk": "https://roll20.net/compendium/dnd5e/Giant%20Elk",
    "Giant Frog": "https://roll20.net/compendium/dnd5e/Giant%20Frog",
    "Giant Goat": "https://roll20.net/compendium/dnd5e/Giant%20Goat",
    "Giant Hyena": "https://roll20.net/compendium/dnd5e/Giant%20Hyena",
    "Giant Lizard": "https://roll20.net/compendium/dnd5e/Giant%20Lizard",
    "Giant Octopus": "https://roll20.net/compendium/dnd5e/Giant%20Octopus",
    "Giant Owl": "https://roll20.net/compendium/dnd5e/Giant%20Owl",
    "Giant Poisonous Snake": "https://roll20.net/compendium/dnd5e/Giant%20Poisonous%20Snake",
    "Giant Sea Horse": "https://roll20.net/compendium/dnd5e/Giant%20Sea%20Horse",
    "Giant Spider": "https://roll20.net/compendium/dnd5e/Giant%20Spider",
    "Giant Toad": "https://roll20.net/compendium/dnd5e/Giant%20Toad",
    "Giant Vulture": "https://roll20.net/compendium/dnd5e/Giant%20Vulture",
    "Giant Wasp (Meganeura)": "https://roll20.net/compendium/dnd5e/Giant%20Wasp",
    "Giant Wasp": "https://roll20.net/compendium/dnd5e/Giant%20Wasp",
    "Giant Wasp/Dragonfly": "https://roll20.net/compendium/dnd5e/Giant%20Wasp",
    "Giant Wolf Spider": "https://roll20.net/compendium/dnd5e/Giant%20Wolf%20Spider",
    "Hunter Shark": "https://roll20.net/compendium/dnd5e/Hunter%20Shark",
    "Lion": "https://roll20.net/compendium/dnd5e/Lion",
    "Male Steeder": "https://5e.tools/bestiary/male-steeder-mtf.html",
    "Panther": "https://roll20.net/compendium/dnd5e/Panther",
    "Polar Bear": "https://roll20.net/compendium/dnd5e/Polar%20Bear",
    "Reef Shark": "https://roll20.net/compendium/dnd5e/Reef%20Shark",
    "Rhinoceros": "https://roll20.net/compendium/dnd5e/Rhinoceros",
    "Riding/Draft Horse*": "https://roll20.net/compendium/dnd5e/Riding%20Horse",
    "Saber-Toothed Tiger": "https://roll20.net/compendium/dnd5e/Saber-Toothed%20Tiger",
    "Tiger": "https://roll20.net/compendium/dnd5e/Tiger",
    "Warhorse": "https://roll20.net/compendium/dnd5e/Warhorse",
    "Wolf": "https://roll20.net/compendium/dnd5e/Wolf"
}
